# src/agents/specialized/coder.py
import asyncio
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, Tuple
import logging

from src.core.base_agent import BaseAgent, AgentConfig

logger = logging.getLogger(__name__)


@dataclass
class CodeResult:
    code: str
    language: str
    tests: str
    documentation: str
    errors: List[str]
    iterations: int


@dataclass
class CoderAgent(BaseAgent):
    name: str = "Coder"
    description: str = "Agent specialized in writing and generating code"
    
    default_language: str = "python"
    max_iterations: int = 3
    
    _generated_code: Dict[str, str] = field(default_factory=dict, init=False)
    
    def __init__(self, config: Optional[AgentConfig] = None):
        if config is None:
            config = AgentConfig(name=self.name, description=self.description)
        super().__init__(config)
        self._setup_coding_tools()
    
    def _setup_coding_tools(self):
        self.register_tool("write_code", self._write_code)
        self.register_tool("execute_code", self._execute_code)
        self.register_tool("review_code", self._review_code)
    
    async def _write_code(
        self,
        specification: str,
        language: str = "python"
    ) -> str:
        logger.info(f"Writing {language} code for: {specification}")
        await asyncio.sleep(0.1)
        
        code_template = f'''"""
{specification}
Generated by CoderAgent
"""

def process_data(input_data):
    """
    Process input data according to specification.
    
    Args:
        input_data: Input to process
        
    Returns:
        Processed result
    """
    # Implementation placeholder
    result = {{"processed": True, "data": input_data}}
    return result


if __name__ == "__main__":
    sample_data = {{"key": "value"}}
    result = process_data(sample_data)
    print(result)
'''
        return code_template
    
    async def _execute_code(self, code: str, language: str = "python") -> Dict[str, Any]:
        logger.info(f"Executing {language} code")
        await asyncio.sleep(0.1)
        
        return {
            "success": True,
            "output": "Code executed successfully",
            "error": None
        }
    
    async def _review_code(self, code: str) -> Dict[str, Any]:
        logger.info("Reviewing code")
        await asyncio.sleep(0.1)
        
        issues = []
        suggestions = []
        
        if "TODO" in code:
            issues.append("Code contains TODO items")
        if "pass" in code and code.count("pass") > 2:
            suggestions.append("Consider implementing placeholder logic")
        if "#" not in code and len(code) > 100:
            suggestions.append("Add comments for better readability")
        
        return {
            "issues": issues,
            "suggestions": suggestions,
            "approved": len(issues) == 0
        }
    
    async def think(self, task: str, context: Dict[str, Any]) -> Dict[str, Any]:
        language = context.get("language", self.default_language)
        
        self.update_working_memory("current_task", task)
        self.update_working_memory("language", language)
        
        return {
            "thought": f"Generating {language} code for: {task}",
            "action": "write_code",
            "params": {"specification": task, "language": language}
        }
    
    async def act(self, thought_result: Dict[str, Any]) -> Any:
        action = thought_result.get("action")
        params = thought_result.get("params", {})
        
        if action == "write_code":
            code = await self.use_tool("write_code", **params)
            self.update_working_memory("generated_code", code)
            return code
        elif action == "execute_code":
            return await self.use_tool("execute_code", **params)
        elif action == "review_code":
            return await self.use_tool("review_code", **params)
        
        return None
    
    async def generate_code(
        self,
        specification: str,
        language: Optional[str] = None
    ) -> CodeResult:
        """
        Generate code from a specification.
        
        Args:
            specification: Description of code to generate
            language: Programming language
            
        Returns:
            CodeResult with generated code and tests
        """
        language = language or self.default_language
        
        code = await self._write_code(specification, language)
        
        review = await self._review_code(code)
        
        tests = self._generate_tests(specification, language)
        documentation = self._generate_documentation(specification, language)
        
        errors = review.get("issues", [])
        
        return CodeResult(
            code=code,
            language=language,
            tests=tests,
            documentation=documentation,
            errors=errors,
            iterations=1
        )
    
    def _generate_tests(self, specification: str, language: str) -> str:
        return f'''"""
Unit tests for: {specification}
"""

def test_basic_functionality():
    """Test basic functionality."""
    assert True

def test_edge_cases():
    """Test edge cases."""
    pass

if __name__ == "__main__":
    test_basic_functionality()
    test_edge_cases()
'''
    
    def _generate_documentation(self, specification: str, language: str) -> str:
        return f'''# Code Documentation

## Specification
{specification}

## Language
{language}

## Usage
```python
result = process_data(input_data)
```

## Notes
- Ensure input data is properly validated
- Handle edge cases appropriately
'''


async def example_coder():
    config = AgentConfig(name="CoderAgent", description="Code generation specialist")
    agent = CoderAgent(config)
    
    result = await agent.generate_code(
        specification="Function to calculate fibonacci numbers",
        language="python"
    )
    
    print(f"Language: {result.language}")
    print(f"Errors: {result.errors}")
    print(f"Code:\n{result.code[:200]}...")


if __name__ == "__main__":
    asyncio.run(example_coder())
